data:
  train_csv: data/processed/train.csv
  val_csv: data/processed/val.csv
  test_csv: data/processed/test.csv
  img_dir: data/processed/patches
  img_size: 224

model:
  type: resnet   # or vit
  num_classes: 4  # adjust based on datasets (PCam=2, BreakHis=2, BACH=4)

training:
  outdir: experiments/exp1
  batch_size: 32
  lr: 1e-4
  epochs: 50
  weight_decay: 1e-4
  experiment_name: exp1_resnet50
  use_xai_reg: false   # start simple, you can enable later
